### PR TITLE
Update to 2020.2.6f1

### PR DESCRIPTION
**Pull request by thnewlands**

### CODE REVIEW

**Comment by ZephyrL** [comment]
Hi, sorry for the late reply, I was busy with my work recently, will check this PR soon

**Comment by thnewlands** [comment]
Take your time!! Really cool project.

**Comment by ZephyrL** [comment]
Thanks for your patience :)
Just a question in advance: is there anything specific regarding this Unity version? I was not following the latest release for a while, how about adapt it directly to the 2020-LTS version (2020.3.12f1c1)?

**Comment by thnewlands** [comment]
LTS sounds good! I just noticed I had to do a bit of work to run it on
2020.2.6f1 which is what I was using at the time and wanted to save time
for the next folks. Nothing specific about the version!

**Comment by ZephyrL** [comment]
Good to know! I'll try merging the PR this weekend and upgrade to the LTS.

**Comment by ZephyrL** [comment]
Hello, here are some updates:

I have successfully run the project on the LTS engine, but I find the performance dropped a lot, the FPS shows to be very unstable and some frames take up to 500ms to render.

Through the process, I exclude some code relevant to the Burst compiler, it seems they are written in the outdated style. I'm still unsure whether it has anything to do with the runtime performance, and I'll look further into the problem. 

As I'm aware that the algorithm used in this project relies heavily on CPU (it frequently copies to a texture array somewhere, if I remember correctly), it can also because the engine has evolved through the time while the code needs to be refactored with more efficient graphics APIs.

**Comment by ZephyrL** [comment]
The project is now upgraded to Unity 2021.3, it should be working fine with the LTS version.

**Pull request closed without merging**
